<a href="https://colab.research.google.com/github/boramkim0514/hw/blob/boramkim0514-patch-1/day11_%EC%98%A4%ED%9B%84%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np3 = np.arange(10, 241, 10)

In [ ]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [ ]:
np3.shape

(24,)

In [ ]:
np3.reshape(2, 12)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [ ]:
np333= np3.reshape(2,3,4)

In [ ]:
np333

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

#1문제

In [ ]:
np333[0,0,2]

30

2문제

In [ ]:
np333[0:1,2]

array([[ 90, 100, 110, 120]])

3문제

In [ ]:
np333[1,1:, :2]

array([[170, 180],
       [210, 220]])

4문제

In [128]:
np333[0:2, 1:3, 2:], np333[0:2, 1:3, 2:]

array([[[ 70,  80],
        [110, 120]],

       [[190, 200],
        [230, 240]]])

In [127]:
np333[1, 0, 3] #160 좌표값

160

In [132]:
np333[1, 0, 3] -10 #150으로 치환

150

In [131]:
np333[0:2, 1:3, 2:] 

array([[[ 70,  80],
        [110, 120]],

       [[190, 200],
        [230, 240]]])